services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    
    image: thecodecup-backend:latest
    container_name: thecodecup-backend
    
    ports:
      - "8000:8000"
    
    env_file:
      - .env
    
    restart: unless-stopped